### ISSUE TITLE
volley.ServerError when placing widget

### ISSUE THREAD

**Issue by dpeet** [oryanm/TrelloWidget#1]
Hello!

I've been using the widget for the past couple months and it's worked great.  Today I reflashed my phone, and now I can't get it to work.  I went from stock Android 6 to Cataclysm + Elementalx and when I connect my phone to ADB I get this error

E/Volley: [2444] BasicNetwork.performRequest: Unexpected response code 400 for https://api.trello.com/1/members/me/boards?filter=open&fields=id,name&lists=open&list_fields=id,name&key=b250ef70ccf79ea5e107279a91045e6e&
E/TWidget: com.android.volley.ServerError

Any suggestions to get it working?  Cheers!

**Comment by dpeet** [comment]
Solved, just need to open the app itself first to sign in!

**Comment by OryanMat** [comment]
:+1:
