### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by DTV96Calibre** [oryanm/TrelloWidget#31]
Users that don't login before attempting to add the widget to their home screen see an error. Users believe the app to be bugged because of this. It is not obvious that the app should be first opened and logged into Trello. The login error should instead redirect the user to login to Trello

**Comment by oryanm** [comment]
The error currently says: ` Could not load board data. Please make sure you are logged in and try again.`
Do you have a suggestion for better wording?

**Comment by DTV96Calibre** [comment]
I don't really think it's a wording issue. The error message comes and goes pretty quickly and people just aren't that bright. Maybe remove the "Error was com.volley...." bit at the end if possible to prevent people from thinking there's something wrong with the app at a glance? I think the real solution is opening the app interface instead of showing the error. It already greets and instructs logged out users to login. Other apps solve this problem by opening a settings/login activity when adding a widget

**Comment by oryanm** [comment]
I agree. I've fixed it here c85423b77a43f14bb5721b888a539e2078c7cadf
Thanks.
