### ISSUE TITLE
Update target API level

### ISSUE THREAD

**Issue by MatHazak** [oryanm/TrelloWidget#40]
As you may have noticed by Play Console, the app is currently only available on devices running Android OS at or below the app's target API level (i.e. 28). Any new update must target API level 33 or above. ([Play Console Help](https://support.google.com/googleplay/android-developer/answer/11926878))

I am willing to work on this app and contribute some maintenance and feature code. 
As a starting point, I suggest updating the dependencies and other build configurations.

**Comment by oryanm** [comment]
Yeah I stopped maintaining this since I stopped using trello. 
If you're willing to take it over I'm happy to give you admin access.

**Comment by MatHazak** [comment]
That's fine. But can I count on you for code reviews or issue discussions?
I have created a pull request for this issue #41 
After that, I want to work on the architecture and implement some new components / migrate some current components to make the code more maintainable.

**Comment by oryanm** [comment]
Well as an admin you wont need code reviews. I don't have time to do that. Happy to to discuss whatever every once in a while though.

**Comment by MatHazak** [comment]
Okay. So would you please merge the PR or give me access to do that?

**Comment by oryanm** [comment]
I've added you as collaborator. Let me know if that lets you merge.
I'll also need to add you (email?) to the play console backend.

**Comment by MatHazak** [comment]
All right. I merged the PR ^^
Currently I don't have a Play Console account, but I can get one if needed.

**Comment by oryanm** [comment]
You're gonna need one if you want to publish these changes.

**Comment by MatHazak** [comment]
I'll let you know as soon as I get an account.
