### ISSUE TITLE
Bug? Tapping card title fails to open app?

### ISSUE THREAD

**Issue by PJRanson** [oryanm/TrelloWidget#44]
Tapping the card title in the Widget For Trello App fails to open the card in Trello.

Repro

1. Install Widget for Trello 
2. Install Trello 
3. Sign in to both 
4. Add Widget to home screen. 
5. Select Board & List
6. Tap Card Title in List

_Expected result:_ Opens Trello App and associated card...

_Result:_ Android UI requests what app to open link with - (with no option for Trello)

Note: Tapping List Title opens Trello perfectly well... 🤔🤷‍♂️

Device - Pixel 7
OS - Android 14

Widget for Trello - v1.8
Trello - Version 2024.7.3.19946
com.trello

**Comment by MatHazak** [comment]
Just to keep you informed, I have made a PR to fix this and am waiting for @oryanm to review it.
I'm also looking for some UI changes like #30 to be added as an option.
I think it would be a good idea for the new release to have this feature as well.

**Comment by PJRanson** [comment]
> Just to keep you informed, I have made a PR to fix this and am waiting for @oryanm to review it. I'm also looking for some UI changes like #30 to be added as an option. I think it would be a good idea for the new release to have this feature as well.

Thanks @MatHazak. Good to know it’s on the Radar at least. Not über urgent but it does slightly hamstring one of widget’s critical features - hence raising it. 

Personally, I don’t mind the current UI as it’s simple and unintrusive, but I suppose having an option to toggle additional UI functionality/elements would be a nice to have. 

Cheers. 
Pete

**Comment by luketych** [comment]
Please fix this

**Comment by luketych** [comment]
> Just to keep you informed, I have made a PR to fix this and am waiting for @oryanm to review it.
> I'm also looking for some UI changes like #30 to be added as an option.
> I think it would be a good idea for the new release to have this feature as well.

Can I manually apply the pr? Do you have a link to it?

**Comment by MatHazak** [comment]
> Can I manually apply the pr? Do you have a link to it?

The PR has already been merged. All we need now is a new build of the app. I think it would be great if @oryanm could build and release a new version on Github, then I could submit a new update to F-Droid as well.
Anyway, you can build the binary apk by Android SDK (using Android Studio or Command-Line Tools), which will also need to download some dependencies.

**Comment by oryanm** [comment]
@MatHazak if you're still around, feel free to submit the fdroid update (thank you).
Closing this now.
