### ISSUE TITLE
Build and release by GitHub Workflows

### ISSUE THREAD

**Issue by MatHazak** [oryanm/TrelloWidget#47]
I'd like to suggest a GitHub workflow to build and release the app. This will make it easier to update the app on both GitHub and F-Droid.
You just need to add the signing secrets to the repo settings so that the app can be updated on F-Droid with the same sign you used before.

**Comment by oryanm** [comment]
That's a good idea. If you're willing to take it over, let me know and I'll upload the secrets.

**Comment by MatHazak** [comment]
I think I would be around for some maintenance and feature updates, but not sure when I would be working on it. I have added the build workflow to my fork [here](https://github.com/MatHazak/TrelloWidget/commit/1e7d4f38796f752dc1863a0ee36c4519eace6a77). you just need to add this secrets to the repo:
```
signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
alias: ${{ secrets.ANDROID_ALIAS }}
keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
```

**Comment by oryanm** [comment]
Alright, the secrets are there..
![image](https://github.com/user-attachments/assets/806c32ee-a49a-4ae2-bcec-82dae9261556)
Note that I named the alias one `ANDROID_KEY_ALIAS`

**Comment by oryanm** [comment]
The build failed. Any idea why?
https://github.com/oryanm/TrelloWidget/actions/runs/12139718714/job/33847936357#step:7:978

**Comment by MatHazak** [comment]
I released the same version and the build [was successful](https://github.com/MatHazak/TrelloWidget/actions/runs/12158534927). 
It seems like the problem is with your secret values. 
Did you encode your signing key in Base64 before submitting it as `ANDROID_SIGNING_KEY`?

**Comment by oryanm** [comment]
> Did you encode your signing key in Base64 

I did not 🤷‍♂️

**Comment by MatHazak** [comment]
Sorry I didn't point that out.
`ANDROID_SIGNING_KEY` should be Base64 encoded.
