### ISSUE TITLE
How can I add the Widget?

### ISSUE THREAD

**Issue by alwinmark** [oryanm/TrelloWidget#6]
I installed the app, logged me in, but somehow I cant find the widget (only the official trello widgets). Is there a trick?

**Comment by oryanm** [comment]
It should show up in the widget drawer just like any other widget. Of course not next to the official widgets, since it's a different app.

**Comment by oryanm** [comment]
did you find it?

**Comment by alwinmark** [comment]
no sorry... its not in the list of the other widgets, so I uninstalled it completely

**Comment by oryanm** [comment]
what device do you have?
